remember_me: 1
per_page: 16

default_user_image: "user-big.jpg"
default_favicon_image: "elearning.png"

min_time: 0
min_words: 0

words: 20

true_str: "true"
false_str: "false"

time_laster_for_submit: -3
finish_submit: "finish"

small_avatar: "100x100"
mini_avater: "40x40"

max_length_of_content: 1000

filter_words:
  learned: "learned"
  not_learned: "not_learned"
  get_all: "get_all"
